name: Build AmpProfiler Plugin (Cross-Platform)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.27.7'

      - name: Install dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ../AmpProfiler -DCMAKE_BUILD_TYPE=Release

      - name: Build plugin
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload built plugin
        uses: actions/upload-artifact@v4
        with:
          name: AmpProfiler-${{ matrix.os }}
          path: |
            build/**/*.vst3
