name: Build AmpProfiler Plugin (Cross-Platform)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.27.7'

      - name: Install dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Configure from the AmpProfiler subfolder
      - name: Configure CMake
        shell: bash
        run: |
          mkdir -p build
          cd build
          cmake ../AmpProfiler -DCMAKE_BUILD_TYPE=Release

      - name: Build plugin
        shell: bash
        run: |
          cd build
          cmake --build . --config Release

      # Package the .vst3 into a zip for easy download
      - name: Package plugin (.zip)
        shell: bash
        run: |
          set -e
          mkdir -p packages
          shopt -s globstar nullglob
          # Find the first produced .vst3 and copy it to a stable name
          vst3_found=""
          for f in build/**/*.vst3; do
            vst3_found="$f"
            break
          done
          if [ -z "$vst3_found" ]; then
            echo "No .vst3 produced under build/**.vst3"; ls -R build || true
            exit 1
          fi
          echo "Found VST3: $vst3_found"
          cp -R "$vst3_found" "packages/AmpProfiler-${{ matrix.os }}.vst3"
          (cd packages && zip -r "AmpProfiler-${{ matrix.os }}.zip" "AmpProfiler-${{ matrix.os }}.vst3")

      - name: Upload artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: AmpProfiler-${{ matrix.os }}
          path: packages/AmpProfiler-${{ matrix.os }}.zip
          if-no-files-found: error
