name: Build AmpProfiler Plugin (Cross-Platform)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      SOURCE_DIR: AmpProfiler/plugin   # <- your CMakeLists.txt folder
      BUILD_DIR: build

    steps:
      - name: Check out repo (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.27.7'

      - name: Install dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config

      - name: Verify CMakeLists exists
        shell: bash
        run: |
          echo "SOURCE_DIR=$SOURCE_DIR"
          test -f "$SOURCE_DIR/CMakeLists.txt" || { 
            echo "::error file=$SOURCE_DIR::CMakeLists.txt not found. Check SOURCE_DIR."; 
            exit 1; 
          }

      - name: Configure CMake
        shell: bash
        run: |
          mkdir -p "$BUILD_DIR"
          cd "$BUILD_DIR"
          cmake "../$SOURCE_DIR" -DCMAKE_BUILD_TYPE=Release

      - name: Build plugin
        shell: bash
        run: |
          cd "$BUILD_DIR"
          cmake --build . --config Release

      - name: Package plugin (.zip)
        shell: bash
        run: |
          set -e
          mkdir -p packages
          shopt -s globstar nullglob
          vst3_found=""
          for f in "$BUILD_DIR"/**/*.vst3; do
            vst3_found="$f"; break
          done
          if [ -z "$vst3_found" ]; then
            echo "::error::No .vst3 produced under $BUILD_DIR/**.vst3"
            ls -R "$BUILD_DIR" || true
            exit 1
          fi
          echo "Found VST3: $vst3_found"
          cp -R "$vst3_found" "packages/AmpProfiler-${{ matrix.os }}.vst3"
          (cd packages && zip -r "AmpProfiler-${{ matrix.os }}.zip" "AmpProfiler-${{ matrix.os }}.vst3")

      - name: Upload artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: AmpProfiler-${{ matrix.os }}
          path: packages/AmpProfiler-${{ matrix.os }}.zip
          if-no-files-found: error
