name: Build AmpProfiler Plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.27.7'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Upload built plugin
        uses: actions/upload-artifact@v3
        with:
          name: AmpProfiler-Plugins
          path: build/**/*.vst3
